site_name: EducaEnergia - Grupo Knuth
site_url: https://fga0138-mds-ajax.github.io/2026.1-T01-Knuth/
repo_url: https://github.com/FGA0138-MDS-Ajax/2026.1-T01-Knuth
repo_name: 2026.1-T01-Knuth


theme: 
  name: material
  language: pt-BR
  logo: assets/images/icon_educa_energia.png
  favicon: assets/images/icon_educa_energia.png

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences


nav: 
  - Documentos: 
    - Documento de Visão: documentos/doc_visao.md
    - Documento de Arquitetura: documentos/doc_arq.md
  - ATAS: atas/index.md
  - Listas de Presenças: presencas/index.md


