# Generated by Django 5.2.14 on 2026-07-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandeiraTarifaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('verde', 'Verde'), ('amarela', 'Amarela'), ('vermelha_1', 'Vermelha Patamar 1'), ('vermelha_2', 'Vermelha Patamar 2')], help_text='Identificador da bandeira tarifária.', max_length=20, unique=True)),
                ('valor_adicional_reais', models.DecimalField(decimal_places=2, default=0.0, help_text='Acréscimo em R$ por 100 kWh consumidos.', max_digits=8)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição das condições vigentes.')),
                ('ativa', models.BooleanField(default=False, help_text='Indica a bandeira atualmente vigente.')),
            ],
            options={
                'verbose_name': 'Bandeira Tarifária',
                'verbose_name_plural': 'Bandeiras Tarifárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='QuizPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(help_text='Texto da pergunta.')),
                ('alternativas', models.JSONField(default=list, help_text='Lista de strings com as alternativas de resposta.')),
                ('resposta_correta', models.PositiveSmallIntegerField(help_text='Índice (0-based) da alternativa correta.')),
                ('explicacao', models.TextField(blank=True, default='', help_text='Explicação exibida após a resposta.')),
                ('modulo', models.ForeignKey(help_text='Módulo ao qual esta questão pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_perguntas', to='educacao.moduloeducativo')),
            ],
            options={
                'verbose_name': 'Pergunta de Quiz',
                'verbose_name_plural': 'Perguntas de Quiz',
                'ordering': ['modulo', 'id'],
            },
        ),
    ]
