# Generated by Django 5.2.14 on 2026-06-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Simulação de consumo', max_length=120)),
                ('tarifa_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dias_referencia', models.PositiveSmallIntegerField(default=30)),
                ('quantidade_eletrodomesticos', models.PositiveSmallIntegerField(default=0)),
                ('total_consumo_mensal_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumo_medio_mensal_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_custo_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_medio_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes_consumo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemSimulacaoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_eletrodomestico', models.CharField(max_length=120)),
                ('potencia_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_uso_dia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_uso_mes', models.PositiveSmallIntegerField(default=30)),
                ('consumo_diario_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumo_mensal_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('custo_mensal_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='consumo.simulacaoconsumo')),
            ],
            options={
                'ordering': ['-consumo_mensal_kwh'],
            },
        ),
    ]
