# Generated by Django 5.2.14 on 2026-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacaoconsumo',
            name='custo_medio_mensal',
        ),
        migrations.RemoveField(
            model_name='simulacaoconsumo',
            name='dias_referencia',
        ),
        migrations.RemoveField(
            model_name='simulacaoconsumo',
            name='quantidade_eletrodomesticos',
        ),
        migrations.RemoveField(
            model_name='simulacaoconsumo',
            name='tarifa_kwh',
        ),
        migrations.RemoveField(
            model_name='simulacaoconsumo',
            name='total_custo_mensal',
        ),
        migrations.AddField(
            model_name='simulacaoconsumo',
            name='meses_analisados',
            field=models.PositiveBigIntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='ItemSimulacaoConsumo',
        ),
    ]
