# Generated by Django 5.2.14 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0002_remove_simulacaoconsumo_custo_medio_mensal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacaoconsumo',
            name='consumo_medio_mensal_kwh',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='simulacaoconsumo',
            name='total_consumo_mensal_kwh',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
