# Generated by Django 5.2.14 on 2026-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_alter_simulacaoconsumo_consumo_medio_mensal_kwh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('potencia_media_watts', models.PositiveIntegerField(help_text='Potência média em Watts')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece no Top 10 inicial da tela')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
