# Generated by Django 5.2.14 on 2026-06-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0004_eletrodomestico'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='descricao_uso',
            field=models.CharField(default='Tempo médio de uso', help_text='Descrição amigável do uso médio', max_length=120),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='tempo_medio_uso_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Tempo médio de uso em minutos'),
        ),
    ]
