# Generated by Django 5.2.14 on 2026-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0005_eletrodomestico_descricao_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaoconsumo',
            name='custo_estimado_reais',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='simulacaoconsumo',
            name='recomendacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulacaoconsumo',
            name='status_consumo',
            field=models.CharField(default='na_media', max_length=30),
        ),
    ]
