# Generated by Django 5.2.14 on 2026-06-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_id', models.PositiveIntegerField(help_text="ID do módulo — deve corresponder ao 'id' definido nos arquivos JS do front-end (1 a 8).", unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('duracao', models.CharField(help_text="Tempo estimado de leitura, ex: '6 min'.", max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(help_text='Define a sequência na trilha de aprendizagem.')),
                ('ativo', models.BooleanField(default=True, help_text='Módulos inativos não aparecem na listagem pública.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo Educativo',
                'verbose_name_plural': 'Módulos Educativos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='educacao.moduloeducativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_modulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Módulo',
                'verbose_name_plural': 'Progressos de Módulos',
                'ordering': ['modulo__ordem'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
