name: ci
on:
  push:
    branches:
      - docs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs>=1.5.0 mkdocs-material>=9.5.0 mkdocstrings mkdocstrings[python]>=0.24.0 pymdown-extensions>=10.5
      
      - run: mkdocs gh-deploy --force